---

- name: Set GPG key
  apt_key:
    url: "https://insomnia.rest/keys/debian-public.key.asc"
    state: present

- name: Add repository
  apt_repository:
    repo: deb https://dl.bintray.com/getinsomnia/Insomnia /
    filename: insomnia
    state: present
    update_cache: yes

- name: Install Insomnia
  apt:
    name: insomnia
    update_cache: true
